apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: list-source-code
spec:
  inputs:
    resources:
      - name: git
        type: git
  steps:
    - name: list-src
      image: alpine
      command:
        - "ls"
      args:
        - "$(inputs.resources.git.path)"
